### ISSUE TITLE
Issue - If CA with different AWS Account and Shared with another account , issue private certificate. - InvalidateARN Issue and Resource not found

### ISSUE THREAD

**Issue by AppExperts2005** [awsdocs/aws-private-ca-user-guide#5]
CA Account ARN : arn:aws:acm-pca:ca-central-1:ACCOUNTA:certificate-authority/XXXXXXXXXX-CAID
Cert ACCOUNT ARN:arn:aws:acm-pca:ca-central-1:ACCOUNTB:certificate/XXXXXXXXXX-CERTID

HOW TO GET ACCESS CERTIFICATE in GETCERTIFICATE.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
